In [3]:
# Q4-1.py
n1 = int(input('시작 수를 입력하세요 : '))
n2 = int(input('끝 수를 입력하세요 : '))

sum = 0
for i in range(n1, n2+1) :
    if i%5 != 0 :
        sum += i

print('-' * 50)
print('%d에서 %d까지 5의 배수가 아닌 수의 합계 : %d' % (n1, n2, sum))

시작 수를 입력하세요 : 100
끝 수를 입력하세요 : 200
--------------------------------------------------
100에서 200까지 5의 배수가 아닌 수의 합계 : 12000

In [4]:
# Q4-2.py
number = input('하이픈(-)을 포함한 휴대폰 번호를 입력하세요: ') 

for x in number :
    if x != '-' :
        print('%s' % x, end='')

하이픈(-)을 포함한 휴대폰 번호를 입력하세요: 010-1234-5678
01012345678

In [1]:
# Q4-3.py
phone = input('하이픈(-)을 뺀 11자리의 휴대폰 번호를 입력하세요: ') 

number = '';
for i in range(0, len(phone)) :
    if i == 2 :
        number = number + (phone[2]+'-')
    elif i == 6 :
        number = number + (phone[6]+'-')
    else :
        number = number + phone[i]

print(number)

하이픈(-)을 뺀 11자리의 휴대폰 번호를 입력하세요: 01033334444
010-3333-4444

In [13]:
# Q4-4.py
print('-' * 60) 
print('센티미터(cm) 인치(inch)   피트(ft)    야드(yd)')
print('-' * 60) 

for cm in range(10, 201, 10) : 
    inch = cm * 0.393701 
    ft = cm * 0.032808
    yd = cm * 0.010936
    print('%8d  %10.1f %10.1f  %10.1f' % (cm, inch, ft, yd))   
     
print('-' * 60)

------------------------------------------------------------
센티미터(cm) 인치(inch)   피트(ft)    야드(yd)
------------------------------------------------------------
      10         3.9        0.3         0.1
      20         7.9        0.7         0.2
      30        11.8        1.0         0.3
      40        15.7        1.3         0.4
      50        19.7        1.6         0.5
      60        23.6        2.0         0.7
      70        27.6        2.3         0.8
      80        31.5        2.6         0.9
      90        35.4        3.0         1.0
     100        39.4        3.3         1.1
     110        43.3        3.6         1.2
     120        47.2        3.9         1.3
     130        51.2        4.3         1.4
     140        55.1        4.6         1.5
     150        59.1        4.9         1.6
     160        63.0        5.2         1.7
     170        66.9        5.6         1.9
     180        70.9        5.9         2.0
     190        74.8        6.2         2.1
     200        78.7        6.6         2.2
------------------------------------------------------------

In [20]:
# Q4-5.py
print('-' * 40) 
print('킬로그램(kg) 파운드(lb)   온스(oz)')
print('-' * 40) 

for kg in range(10, 101, 5) : 
    lb = kg * 2.204623
    oz = kg * 35.273962
    print('%8d  %10.1f %10.1f' % (kg, lb, oz))   
     
print('-' * 40)

----------------------------------------
킬로그램(kg) 파운드(lb)   온스(oz)
----------------------------------------
      10        22.0      352.7
      15        33.1      529.1
      20        44.1      705.5
      25        55.1      881.8
      30        66.1     1058.2
      35        77.2     1234.6
      40        88.2     1411.0
      45        99.2     1587.3
      50       110.2     1763.7
      55       121.3     1940.1
      60       132.3     2116.4
      65       143.3     2292.8
      70       154.3     2469.2
      75       165.3     2645.5
      80       176.4     2821.9
      85       187.4     2998.3
      90       198.4     3174.7
      95       209.4     3351.0
     100       220.5     3527.4
----------------------------------------

In [23]:
# Q4-6.py
number = input('숫자를 입력하세요 : ') 

total = 0 

for a in number : 
   a = int(a) 
   if a % 2 == 1 : 
      total += 1 

print('입력된 숫자 중 홀수의 개수 : %d개' % total)

숫자를 입력하세요 : 3049894
입력된 숫자 중 홀수의 개수 : 3개

In [29]:
# Q4-7.py
for i in range(1,11) :
    for j in range(1, i+1) :
        print('*', end='')
    print()

*
**
***
****
*****
******
*******
********
*********
**********

In [27]:
# Q4-8.py
for i in range(1,11) :
    for j in range(1, 10-i+1) :
        print(' ', end='')
    for k in range(1, i+1) :
        print('*', end='')
    print()

         *
        **
       ***
      ****
     *****
    ******
   *******
  ********
 *********
**********

In [34]:
# Q4-9.py
print('-' * 30) 
print('     섭씨     화씨')
print('-' * 30) 

c = -20
while c < 41 :
    f = c * 9.0/ 5.0 + 32.0 
    print('%8d  %8.1f' % (c, f))

    c +=1
     
print('-' * 30)

------------------------------
     섭씨     화씨
------------------------------
     -20      -4.0
     -19      -2.2
     -18      -0.4
     -17       1.4
     -16       3.2
     -15       5.0
     -14       6.8
     -13       8.6
     -12      10.4
     -11      12.2
     -10      14.0
      -9      15.8
      -8      17.6
      -7      19.4
      -6      21.2
      -5      23.0
      -4      24.8
      -3      26.6
      -2      28.4
      -1      30.2
       0      32.0
       1      33.8
       2      35.6
       3      37.4
       4      39.2
       5      41.0
       6      42.8
       7      44.6
       8      46.4
       9      48.2
      10      50.0
      11      51.8
      12      53.6
      13      55.4
      14      57.2
      15      59.0
      16      60.8
      17      62.6
      18      64.4
      19      66.2
      20      68.0
      21      69.8
      22      71.6
      23      73.4
      24      75.2
      25      77.0
      26      78.8
      27      80.6
      28      82.4
      29      84.2
      30      86.0
      31      87.8
      32      89.6
      33      91.4
      34      93.2
      35      95.0
      36      96.8
      37      98.6
      38     100.4
      39     102.2
      40     104.0
------------------------------

In [38]:
# Q4-10.py
i = 200
count = 0
while i < 601 :
    if i % 3 != 0 :
        print('%d ' % i, end='')
        count += 1
        if count % 8 == 0 :
            print()
    i += 1

200 202 203 205 206 208 209 211
212 214 215 217 218 220 221 223
224 226 227 229 230 232 233 235
236 238 239 241 242 244 245 247
248 250 251 253 254 256 257 259
260 262 263 265 266 268 269 271
272 274 275 277 278 280 281 283
284 286 287 289 290 292 293 295
296 298 299 301 302 304 305 307
308 310 311 313 314 316 317 319
320 322 323 325 326 328 329 331
332 334 335 337 338 340 341 343
344 346 347 349 350 352 353 355
356 358 359 361 362 364 365 367
368 370 371 373 374 376 377 379
380 382 383 385 386 388 389 391
392 394 395 397 398 400 401 403
404 406 407 409 410 412 413 415
416 418 419 421 422 424 425 427
428 430 431 433 434 436 437 439
440 442 443 445 446 448 449 451
452 454 455 457 458 460 461 463
464 466 467 469 470 472 473 475
476 478 479 481 482 484 485 487
488 490 491 493 494 496 497 499
500 502 503 505 506 508 509 511
512 514 515 517 518 520 521 523
524 526 527 529 530 532 533 535
536 538 539 541 542 544 545 547
548 550 551 553 554 556 557 559
560 562 563 565 566 568 569 571
572 574 575 577 578 580 581 583
584 586 587 589 590 592 593 595
596 598 599

In [1]:
# Q4-11.py
sentence = input('문장을 입력해 주세요 : ') 

i = len(sentence) - 1

while i >= 0 :
    if sentence[i] == ' ' :
        print('-', end='')
    else :
         print('%s' % sentence[i], end='')

    i -= 1

문장을 입력해 주세요 : 쥐 구멍에 볕 들 날 있다.
.다있-날-들-볕-에멍구-쥐